### ISSUE TITLE
Reload page 

### ISSUE THREAD

**Issue by ShriramK** [HimbeersaftLP/ios-safari-remote-debug-kit#10]
Device - iPad 2 
host OS - Windows 11

Upon accessing  Reload page button
it gives the error below - 

Web Inspector encountered an internal error.

These uncaught exceptions caused this problem 
Uncaught TypeError:​ Cannot read properties of undefined (reading 'reload')​ (at Main.js:​2536:​22)​
    ?​ @ TypeError:​ Cannot read properties of undefined (reading 'reload')​
    ?​ @ Main.js:​2536:​22)​
    ?​ @ Object.js:​134:​31)​
    ?​ @ Object.js:​142:​9)​
    ?​ @ ButtonNavigationItem.js:​208:​14)​
    ?​ @ ButtonNavigationItem.js:​187:​14)​
    
======

Please see the attached files
![ApplicationIssueNote63j](https://user-images.githubusercontent.com/780653/194903200-c91386ce-fbb4-42b6-8f69-7d153f94fad1.png)
![ApplicationIssueNote63i](https://user-images.githubusercontent.com/780653/194903210-41a6e59e-a426-44b8-b951-36194b604e71.png)

**Comment by HimbeersaftLP** [comment]
Hi, thank you for creating an issue!
The problem you are seeing here is most likely caused by a failed WebSocket connection. The refresh button not working is just a side effect of that.
I just added some troubleshooting instructions for this issue to the readme, would you mind trying that and telling me if helps?
https://github.com/HimbeersaftLP/ios-safari-remote-debug-kit#troubleshooting (the second tip)
