### ISSUE TITLE
scrollIntoViewIfNeeded is not a function 

### ISSUE THREAD

**Issue by will-weng** [HimbeersaftLP/ios-safari-remote-debug-kit#21]
I'm getting Internal errors on Web Inspector when running:
`TypeError:​ tagSpans[0]​.scrollIntoViewIfNeeded is not a function (at DOMTreeElement.js:​702:​25)​`
I've seen it appear in other areas of web inspector

**Comment by HimbeersaftLP** [comment]
wdym by running, you mean the error appears immediately?
What browser are you using and does it happen on any site you debug?

**Comment by will-weng** [comment]
it might have been cause of using fire fox, I spend a long time installing and reinstalling while getting similar errors.
I do remember using chrome and getting similar errors too.
It's working a day later now, no errors while debugging any sites on the ipad.

**Comment by HimbeersaftLP** [comment]
I tried for hours to get it to work in Firefox, but even after getting it to load, as soon as I did anything I ran into another dozen webkit and chromium specific legacy features that I'd need to make polyfills for, so I gave up. Ideally you'd use Gnome Web if you're on Linux, because that uses the Webkit engine the debugger was made for. Chromium should work as well, the specific method mentioned in your issue should be implemented in Chromium based browsers, I tested it a while back.
