### ISSUE TITLE
Debugging within VS Code

### ISSUE THREAD

**Issue by frankmarazita** [HimbeersaftLP/ios-safari-remote-debug-kit#22]
Is there any current way to do live debugging similar to what is mentioned [here](https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/blob/21bfd8dc6b3e128c1a617ae655fba6a956e49f45/README.md#using-with-microsoft-vs-code) in VS Code? I have spent a good chunk of time trying to get an implementation of it working and am just unsure if it's possible. Thanks!

**Comment by HimbeersaftLP** [comment]
Since the Webkit debugging protocol and the Chrome debugging protocol diverged, debugging from Chrome and VSCode doesn't work natively anymore.
You'd have to manually implement an adapter from the Webkit protocol to [DAP](https://microsoft.github.io/debug-adapter-protocol/), for example by modifying the current Chrome and Node debugging adapter: https://github.com/microsoft/vscode-js-debug
This is what the remotedebug-ios-webkit-adapter and [Microsoft's old official Safari debugging extension](https://github.com/microsoft/vscode-ios-web-debug) used to do, but they both aren't maintained anymore.
The advantage of this project here is that it basically doesn't require any maintenance, because I just use the debugger that comes with Webkit and don't need to keep up with changes to their protocol.
